# Generated by Django 2.0.5 on 2018-05-30 06:06

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('mobile', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
            managers=[
                ('all_employees', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.IntegerField()),
                ('premium_term', models.CharField(choices=[('Q', 'Quarterly'), ('H', 'Half-Yearly'), ('A', 'Annual')], max_length=1)),
                ('premium_amount', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lic.Client')),
            ],
        ),
    ]
